### ISSUE TITLE
converge similar files into folders

### ISSUE THREAD

**Issue by Souravirus** [Souravirus/specialPrograms#13]

**Comment by Souravirus** [comment]
files like convexhull.cpp , trie.cpp  and KMP which can be converged into some group are just lying outside please converge them to some particular folders

**Comment by kodinglife** [comment]
Hey, I'm curious. Won't moving files break things. Are we expected to fix the links or just move the files to folders?

**Comment by Souravirus** [comment]
@kodinglife Moving files to folders would makes the programs accessible in an easier way. So, it would be surely beneficial for programmers

**Comment by sirjan13** [comment]
I can do this.Just tell me whats this dp_with_maps program doing

**Comment by Souravirus** [comment]
@sirjan13 it is an implementation of dynamic programming with map
