### ISSUE TITLE
Please remove the programs from root directory which are been included in sub folders

### ISSUE THREAD

**Issue by Souravirus** [Souravirus/specialPrograms#31]
Some programs like gogi_tictac.cpp and tictac.cpp are still lying in the root directory which are already included in subfolders like game. So please remove those files.

**Comment by Vehemos** [comment]
@Souravirus  on it

**Comment by Souravirus** [comment]
@Vehemos Please see the readme.md. It has mixed up the previous readme with current so please correct it.

**Comment by Vehemos** [comment]
@Souravirus Please don't accept my current PR for now, I will re-edit it

**Comment by Souravirus** [comment]
Okk @Vehemos
