### ISSUE TITLE
Add a square root decomposition program 

### ISSUE THREAD

**Issue by Souravirus** [Souravirus/specialPrograms#50]

**Comment by octamois** [comment]
I am working on this @Souravirus

**Comment by Souravirus** [comment]
Okk thanks @octamois

**Comment by sirjan13** [comment]
Can i add solution for this : www.spoj.com/problems/DQUERY ?
It used MO's Algorithm (implementing sqrt decomposition)

**Comment by Souravirus** [comment]
Yeah @sirjan13 it would be great

**Comment by sirjan13** [comment]
Plz Review PR #62
