### ISSUE TITLE
Add Artificial Intelligence directory for BFS, DFS, Greedy, and A* search algorithms?

### ISSUE THREAD

**Issue by Troesler95** [Souravirus/specialPrograms#54]
I love the premise of this project, it could be a great resource for students everywhere!

 I have been working lately on AI-based search algorithms (some involving heuristics-based approaches) in C++. Would this be something you'd like to see here? If so I can work on adding this work to the project!

**Comment by Souravirus** [comment]
@Troesler95 It would be great if you add Artificial Intelligence based algorithms into this project.

**Comment by Troesler95** [comment]
Great! @Souravirus I'll get working on it

**Comment by Souravirus** [comment]
@Troesler95 we have last heard of you 3 days ago. Do you really want to contribute to this issue, or should I close this issue.
