### ISSUE TITLE
Implementation of Fenwick tree required here

### ISSUE THREAD

**Issue by Souravirus** [Souravirus/specialPrograms#59]
Our project is now a collection of very good algorithms but still there are some algos which have not been implemented. So any help would be appreciated.

**Comment by sirjan13** [comment]
will solution to problem requiring fenwick tree work to ilustrate the use of fenwick tree. I would mention the link of the problem as a comment in the code

**Comment by Souravirus** [comment]
Yeah it would be perfect to give the code of a solution @sirjan13

**Comment by sirjan13** [comment]
Code for sum in a range of array by fenwickTree. Plz review PR #61
